///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestGitIntegration2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestGitIntegration2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0.0")]
    [RepositoryFolder("b1626361-ff24-4147-82d9-1bdfdb5e31f4")]
    public partial class TestGitIntegration2Repository : RepoGenBaseFolder
    {
        static TestGitIntegration2Repository instance = new TestGitIntegration2Repository();

        /// <summary>
        /// Gets the singleton class instance representing the TestGitIntegration2Repository element repository.
        /// </summary>
        [RepositoryFolder("b1626361-ff24-4147-82d9-1bdfdb5e31f4")]
        public static TestGitIntegration2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestGitIntegration2Repository() 
            : base("TestGitIntegration2Repository", "/", null, 0, false, "b1626361-ff24-4147-82d9-1bdfdb5e31f4", ".\\RepositoryImages\\TestGitIntegration2Repositoryb1626361.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b1626361-ff24-4147-82d9-1bdfdb5e31f4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0.0")]
    public partial class TestGitIntegration2RepositoryFolders
    {
    }
#pragma warning restore 0436
}