///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace TestGitIntegration1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestGitIntegration1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0.0")]
    [RepositoryFolder("331c7386-f98b-4f51-bb26-d5a0c8db9de0")]
    public partial class TestGitIntegration1Repository : RepoGenBaseFolder
    {
        static TestGitIntegration1Repository instance = new TestGitIntegration1Repository();

        /// <summary>
        /// Gets the singleton class instance representing the TestGitIntegration1Repository element repository.
        /// </summary>
        [RepositoryFolder("331c7386-f98b-4f51-bb26-d5a0c8db9de0")]
        public static TestGitIntegration1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestGitIntegration1Repository() 
            : base("TestGitIntegration1Repository", "/", null, 0, false, "331c7386-f98b-4f51-bb26-d5a0c8db9de0", ".\\RepositoryImages\\TestGitIntegration1Repository331c7386.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("331c7386-f98b-4f51-bb26-d5a0c8db9de0")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0.0")]
    public partial class TestGitIntegration1RepositoryFolders
    {
    }
#pragma warning restore 0436
}